cassandra:
  public_ip: localhost
  user_name: cassandra
  password:  cassandra

log:
  level: info
  output: logs/app_log.%Y-%m-%d.log #logs/access_log-%Y-%m-%d-%H-%M-%S.log
  map:
    time: "@timestamp"
    msg: message